### ISSUE TITLE
Fix flaky test TestRecordShapeAlignment

### ISSUE THREAD

**Issue by chtenb** [Rubjerg/Graphviz.NetWrapper#30]
The test TestRecordShapeAlignment fails on the github test server, but passes locally. Figure out why.
For some reason calling dot.exe directly on dot files does not give a wrong alignment on the github server.

**Comment by Chiel92** [comment]
The recordshape alignment only fails when it is called from a .NET process, even when the logic completely resides in C++ code.

Possible investigation vector: see if config6 generation is the same on both machines if you do it from a .NET process using p/Invokes.

**Comment by chtenb** [comment]
It's an upstream issue: https://gitlab.com/graphviz/graphviz/-/issues/1610
