### ISSUE TITLE
Generation bug

### ISSUE THREAD

**Issue by Ephron-WL** [Rubjerg/Graphviz.NetWrapper#50]
Given this DOT graph:
```
digraph {
compound=true;
node [shape=Mrecord]
rankdir="LR"

subgraph "clusterOpen"
	{
	label = "Open"
"Assigned" [label="Assigned|exit / OnDeassigned"];
}
"Deferred" [label="Deferred|entry / Function"];
"Closed" [label="Closed"];

"Open" -> "Assigned" [style="solid", label="Assign / OnAssigned"];
"Assigned" -> "Assigned" [style="solid", label="Assign"];
"Assigned" -> "Closed" [style="solid", label="Close"];
"Assigned" -> "Deferred" [style="solid", label="Defer"];
"Deferred" -> "Assigned" [style="solid", label="Assign / OnAssigned"];
 init [label="", shape=point];
 init -> "Open"[style = "solid"]
}
```

Graphiviz generates this diagram:
![image](https://user-images.githubusercontent.com/43553209/213775457-17fa44c3-b47a-4baf-9c84-28557620a30e.png)

Using this code:
``` 
	var root = RootGraph.FromDotString(bug.ToDotGraph());
	root.ComputeLayout();
	root.ToSvgFile(@"c:\temp\diagram.svg");
```

It generates this diagram:
![image](https://user-images.githubusercontent.com/43553209/213775676-4a475ff9-64cc-4c9d-8011-c52132f3f95a.png)

The Open text is missing.

**Comment by chtenb** [comment]
Thanks for the report.

Possible related: https://github.com/Rubjerg/Graphviz.NetWrapper/issues/30

Calling graphviz code from within a .NET process via p/Invoke seems to induce strange behavior sometimes. It is currently unclear to me why that happens. I'd love to hunt this nagging issue down at some point, but I'm a little short on time these days.

**Comment by Ephron-WL** [comment]
I understand it can be difficult if not impossible to support open source projects, considering they don't pay the rent.  You've done an excellent job in developing this library.  It looks like you put in a lot of work.

The process of converting a DOT file to SVG using p/invoke seems to be to call the native functions gvLayout, gvRender, and gvRenderFilename, making me think the problem is not in p/invoke but the native libraries that accompany the project.  Maybe they have a bug?

**Comment by chtenb** [comment]
Yes that could be. But I vaguely remember that I tried to reproduce by calling these functions from C++ directly, after which I couldn't reproduce the bug anymore.

**Comment by chtenb** [comment]
https://gitlab.com/graphviz/graphviz/-/issues/2434
