### ISSUE TITLE
Feature Request: ToSvgFile overload

### ISSUE THREAD

**Issue by Ephron-WL** [Rubjerg/Graphviz.NetWrapper#52]
void ToSvgFile(Stream stream)

It would be nice to obtain the SVG as a stream instead of a file.

**Comment by chtenb** [comment]
PRs are welcome, but I think it's not completely trivial. I think you will have to get the export as a string first using one of the `rendering` functions in `gvc.h` or something, and then stream that string into whatever stream object, while making sure that the resources involved are correctly freed. It is possible to add helper functions in Main.cpp.

**Comment by Ephron-WL** [comment]
I'd be happy to make the change and submit a PR, but I want to ensure we get this rendering issue fixed before making that investment.   I used the wrapper on another DOT file and there was a cluster of nodes that did not include a rendering of the label.  The only pattern I see is that the nodes are ordered to be the first ones to be rendered.  If you guys can fix this issue, possibly through an update of the unmanaged libraries, then I'll definitely work on adding the overload.
