### ISSUE TITLE
Assembly.GetExecutingAssembly().Location is empty for self-contained (single file) apps

### ISSUE THREAD

**Issue by modery** [Rubjerg/Graphviz.NetWrapper#78]
I'm using this library in a self-contained .NET application. During development, everything was working well, but once I published a package I got the following error:
![image](https://github.com/Rubjerg/Graphviz.NetWrapper/assets/15896715/7db7d58b-7c99-4339-aa03-badf8e1d90de)

The following code is the "culprit" here:
` string exeDirectory = AppDomain.CurrentDomain.RelativeSearchPath
            ?? Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);`
https://github.com/Rubjerg/Graphviz.NetWrapper/blob/master/Rubjerg.Graphviz/GraphvizCommand.cs#L51

The problem is that `Assembly.GetExecutingAssembly().Location` is empty for single file apps, thus the Path.Combine call right after the above code fails.

Using `System.AppContext.BaseDirectory` as an additional option should work from what I understand, so `    string exeDirectory = AppDomain.CurrentDomain.RelativeSearchPath
            ?? Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)
            ?? Path.GetDirectoryName(System.AppContext.BaseDirectory);`
might be the right way to fix this issue

**Comment by chtenb** [comment]
That sounds like a simple improvement with no drawbacks. So if you have a solution that works in your situation, feel free to provide a PR and I'll merge it in.

**Comment by modery** [comment]
Can you also publish a new nuget package again? Thank you!
