### ISSUE TITLE
Use Graphviz JSON output instead of C++ GraphvizWrapper

### ISSUE THREAD

**Issue by PolarGoose** [Rubjerg/Graphviz.NetWrapper#89]
I see that this project has a `GraphvizWrapper` project written in C++ to get information about the graph, such as coordinates, edge paths, etc.
Wouldn't it be easier to make Graphviz produce a [JSON output](https://graphviz.org/docs/outputs/json) and parse from C# directly?

**Comment by chtenb** [comment]
It's a different strategy that would involve writing a lot of parsers for dot, xdot etc. Not wrong, just a different approach.
