### ISSUE TITLE
Get DllNotFoundException 

### ISSUE THREAD

**Issue by TihonchukArtyom89** [Rubjerg/Graphviz.NetWrapper#93]
Hi! I recently started use NetWrapper and get this exception "Unable to load DLL 'GraphvizWrapper.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)" when create  new oriented graph.

**Comment by chtenb** [comment]
Can you describe how you deployed this library? Both the projects themselves and the nuget package [are tested and everything appears fine.](https://github.com/Rubjerg/Graphviz.NetWrapper/actions/runs/11797933119/job/32862990598)

**Comment by TihonchukArtyom89** [comment]
I add the NuGet package to the project on the link : [I'm adding the NuGet package to the project using the link:](url)

**Comment by chtenb** [comment]
We have tests in place that specifically test that scenario. See

https://github.com/Rubjerg/Graphviz.NetWrapper/tree/master/Rubjerg.Graphviz.TransitiveNugetTest
and https://github.com/Rubjerg/Graphviz.NetWrapper/tree/master/Rubjerg.Graphviz.NugetTest

Those tests are green. Can you look what you are doing differently than those projects?

**Comment by TihonchukArtyom89** [comment]
I am sorry. I do not add link to archive where is throwing exception. Here it is : https://dropmefiles.com/tmtkL
To use Graphviz.NetWrapper I simple add NuGet package. And in project I see added graphviz files, but when I start project exception is throwing.

**Comment by chtenb** [comment]
I don't have time to download and debug your code. The examples I linked show a working scenario, so I think you should be able to figure out why your situation doesn't work. If you find there is a bug in this package, please post it here. Otherwise you can close the issue.

**Comment by TihonchukArtyom89** [comment]
Ok. I get it. Did I understand correctly that to use the Graphviz.NetWrapper as the NuGet package you just need to install it and nothing more?

**Comment by chtenb** [comment]
Yes, just like the projects I linked to. Try cloning this repository and opening those projects to see it in action. There's nothing more I can explain.

**Comment by TihonchukArtyom89** [comment]
Thank you for your time

**Comment by chtenb** [comment]
@TihonchukArtyom89 It just occurred to me that you need to have the VC runtime installed, which you may not have if you pull graphviz as a nuget package. This is not clearly listed in the README, which I will adapt.
